# Auto-labeling configuration for PRs based on file changes

# Frontend related changes
frontend:
  - src/components/**/*
  - src/pages/**/*
  - src/styles/**/*
  - "*.css"
  - "*.scss"

# Backend/API changes
backend:
  - src/api/**/*
  - src/services/**/*
  - src/utils/**/*

# Test changes
tests:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - src/test/**/*
  - "**/__tests__/**/*"

# Documentation changes
documentation:
  - "*.md"
  - docs/**/*
  - ".github/**/*.md"

# CI/CD changes
ci/cd:
  - .github/workflows/**/*
  - ".github/dependabot.yml"
  - "Dockerfile*"
  - docker-compose*.yml

# Configuration changes
config:
  - "*.json"
  - "*.yml"
  - "*.yaml"
  - "*.toml"
  - ".*rc*"
  - eslint.config.js
  - vitest.config.ts
  - vite.config.ts
  - tsconfig*.json

# Dependencies
dependencies:
  - package.json
  - package-lock.json
  - yarn.lock

# Core functionality
core:
  - src/flow/**/*
  - src/nodes/**/*
  - src/planner/**/*

# Storage and data
storage:
  - src/shared/storage.ts
  - src/run-center/**/*

# Ideas and blueprints
ideas:
  - src/ideas/**/*