name: Epic
description: 史诗级需求（跨多个模块/里程碑）
labels: ["type/epic", "status/planning", "project:superflow"]
body:
  - type: input
    id: goal
    attributes:
      label: 目标（一句话）
      placeholder: 例如：打通“想法→蓝图→DAG→运行/修复”闭环
  - type: textarea
    id: scope
    attributes:
      label: 范围（Scope）
      description: 明确包含/不包含
      placeholder: 包含 A/B/C；不包含 X/Y/Z
  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准（Acceptance Criteria）
      placeholder: |-
        - [ ] 场景 1 …
        - [ ] 场景 2 …
  - type: textarea
    id: breakdown
    attributes:
      label: 子任务（Backlog）
      placeholder: Task 1、Task 2（建议用 Feature/Task 模板单建）
  - type: textarea
    id: risks
    attributes:
      label: 风险与对策
  - type: textarea
    id: refs
    attributes:
      label: 参考与文件
      placeholder: |-
        AGENTS.md:xxx
        docs/adr/0003-重构.md:xxx

