name: Feature
description: 新功能/能力（可在 1–3 天内完成）
labels: ['type/feature', 'status/planning', 'project:superflow']
body:
  - type: input
    id: epic
    attributes:
      label: 所属 Epic（可选）
      placeholder: 例如：M1 编排与运行
  - type: dropdown
    id: module
    attributes:
      label: 模块
      options:
        - Studio
        - Flow
        - Inspector
        - Run Center
        - Services
        - Runtime
        - Data
  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      options:
        - P0
        - P1
  - type: textarea
    id: context
    attributes:
      label: 背景/动机
  - type: textarea
    id: scope
    attributes:
      label: 范围（Scope）
      placeholder: 包含/不包含
  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准
      placeholder: |-
        - [ ] …
  - type: textarea
    id: tests
    attributes:
      label: 测试与度量
      placeholder: 单元/集成/性能/指标
  - type: textarea
    id: refs
    attributes:
      label: 参考与文件
