name: Task
description: 可独立交付的小任务（≤ 1 天）
labels: ['type/task', 'status/ready', 'project:superflow']
body:
  - type: dropdown
    id: module
    attributes:
      label: 模块
      options:
        - Studio
        - Flow
        - Inspector
        - Run Center
        - Services
        - Runtime
        - Data
  - type: textarea
    id: scope
    attributes:
      label: 范围（Scope）
  - type: textarea
    id: acceptance
    attributes:
      label: 验收（DoD）
      placeholder: |-
        - [ ] 代码/类型/测试/文档
        - [ ] 无破坏外部契约
  - type: textarea
    id: refs
    attributes:
      label: 参考与文件
