name: 仅自动合并 (无测试)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: 直接合并dependabot PR (跳过测试)
        run: |
          echo "正在合并PR: ${{ github.event.pull_request.html_url }}"
          echo "跳过测试步骤以避免GitHub Actions计费"
          gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}" || echo "合并失败，可能需要手动处理"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}