name: Auto Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: ['main']

permissions:
  contents: read
  pull-requests: read

jobs:
  verify:
    runs-on: ubuntu-latest
    # 只跑检查，不要写权限
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          # 检出 PR 的代码
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm ci
      - run: npm run test
      - run: npm run lint
      - run: npm run format -- --check
      - run: npx grunt

  auto-merge:
    needs: verify
    runs-on: ubuntu-latest
    if: |
      needs.verify.result == 'success' &&
      (
        github.event.pull_request.user.login == 'dependabot[bot]' ||
        github.event.pull_request.user.login == 'codex' ||
        github.event.pull_request.user.login == 'codex[bot]' ||
        contains(github.event.pull_request.labels.*.name, 'auto-merge') ||
        contains(github.event.pull_request.title, '[auto-merge]')
      )
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
