name: Auto Merge

on:
  pull_request:
    types: [labeled]
    branches: [main]
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'auto-merge')) ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    
    steps:
      - name: Auto merge Dependabot PRs
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            
            // Enable auto-merge for dependabot PRs
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash',
              commit_title: `Auto-merge Dependabot PR #${prNumber}`,
              commit_message: 'Automatically merged Dependabot PR'
            });

      - name: Auto merge labeled PRs  
        if: >-
          github.event_name == 'pull_request' && 
          contains(github.event.pull_request.labels.*.name, 'auto-merge') &&
          github.event.pull_request.user.login != 'dependabot[bot]'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            
            // Check if all CI checks pass
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            
            const failedChecks = checks.check_runs.filter(check => 
              check.conclusion !== 'success' && check.conclusion !== null
            );
            
            if (failedChecks.length > 0) {
              console.log('Some checks are still failing, will not auto-merge');
              return;
            }
            
            // Merge the PR
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash',
              commit_title: `Auto-merge PR #${prNumber}`,
              commit_message: 'Automatically merged by CI'
            });
